{% set version = "3.5.1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-robma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RoBMA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RoBMA/RoBMA_{{ version }}.tar.gz
  sha256: 93c53a27580ca5cf0df69387f5f1ef8e436f178e76b9bda78efcdda84c86305a

build:
  ## Jags dependency not availble on windows.
  ## OSX build currently disabled due to problems linking to jags
  skip: true  # [not linux]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - jags

  host:
    - jags
    - r-base
    - r-bh
    - r-dpq
    - r-rdpack
    - r-bridgesampling
    - r-callr
    - r-coda
    - r-extradistr
    - r-psych
    - r-rjags
    - r-runjags
    - r-scales
    - r-bayestools
    - r-ggplot2

  run:
    - jags
    - r-base
    - r-bh
    - r-dpq
    - r-rdpack
    - r-bridgesampling
    - r-callr
    - r-coda
    - r-extradistr
    - r-psych
    - r-rjags
    - r-runjags
    - r-scales
    - r-bayestools
    - r-ggplot2

test:
  commands:
    - $R -e "library('RoBMA')"           # [not win]
    - "\"%R%\" -e \"library('RoBMA')\""  # [win]

about:
  home: https://fbartos.github.io/RoBMA/

  license: GPL-3.0-only
  summary: A framework for estimating ensembles of meta-analytic models (assuming either presence or absence of the effect, heterogeneity, and publication bias) and using Bayesian model averaging to combine them. The ensembles use Bayes factors to test for the presence or absence of the individual components (e.g., effect
    vs. no effect) and model-averages parameter estimates based on posterior model probabilities (Maier, Bartoš & Wagenmakers, 2020, <doi:10.31234/osf.io/u4cns>). The user can define a wide range of non-informative or informative priors for the effect size, heterogeneity, and weight functions. The package provides convenient
    functions for summary, visualizations, and fit diagnostics.

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
