{% set version = "4.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-robma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RoBMA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RoBMA/RoBMA_{{ version }}.tar.gz
  sha256: 9fc78da8b60c0b8f86e14fd9529dabe3c4e1ba974e9c9e9d3ca622a3fa4763ce

build:
  ## Jags dependency not availble on windows.
  ## OSX build currently disabled due to problems linking to jags
  skip: true  # [not linux]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - jags
  host:
    - jags
    - r-base
    - r-bayestools >=0.3.0
    - r-mass
    - r-rdpack
    - r-bridgesampling
    - r-coda
    - r-ggplot2
    - r-loo
    - r-mvtnorm
    - r-rjags
    - r-rlang
    - r-runjags
    - r-scales
  run:
    - jags
    - r-base
    - r-bayestools >=0.3.0
    - r-mass
    - r-rdpack
    - r-bridgesampling
    - r-coda
    - r-ggplot2
    - r-loo
    - r-mvtnorm
    - r-rjags
    - r-rlang
    - r-runjags
    - r-scales

test:
  commands:
    - $R -e "library('RoBMA')"           # [not win]
    - "\"%R%\" -e \"library('RoBMA')\""  # [win]

about:
  home: https://fbartos.github.io/RoBMA/
  license: GPL-3.0-only
  summary: "A framework for Bayesian meta-analysis, including model estimation, prior specification,
    model comparison, prediction, summaries, visualizations, and diagnostics. The package
    fits single and model-averaged meta-analytic, meta-regression, multilevel, publication
    bias adjusted, and generalized linear mixed models The model-averaged meta-analytic
    models combine competing models based on their predictive performance, weight inference
    by posterior model probabilities, and test model components using Bayes factors
    (e.g., effect vs. no effect; Barto\u0161 et al., 2022, <doi:10.1002/jrsm.1594>;
    Maier, Barto\u0161 & Wagenmakers, 2022, <doi:10.1037/met0000405>; Barto\u0161 et
    al., 2025, <doi:10.1037/met0000737>). Users can specify flexible prior distributions
    for effect sizes, heterogeneity, publication bias (including selection models and
    PET-PEESE), and moderators."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
