{% set version = "3.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-robma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RoBMA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RoBMA/RoBMA_{{ version }}.tar.gz
  sha256: cdb27398fa9761dcd978ec10c7b3a8779cfbac007d8438750b3b20de399e4f9d

build:
  ## Jags dependency not availble on windows.
  ## OSX build currently disabled due to problems linking to jags
  skip: true  # [not linux]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - jags
  host:
    - r-base
    - r-bayestools >=0.2.17
    - r-rdpack
    - r-coda
    - r-ggplot2
    - r-mvtnorm
    - r-rjags
    - r-rlang
    - r-runjags
    - r-scales
    - jags
  run:
    - r-base
    - r-bayestools >=0.2.17
    - r-rdpack
    - r-coda
    - r-ggplot2
    - r-mvtnorm
    - r-rjags
    - r-rlang
    - r-runjags
    - r-scales
    - jags

test:
  commands:
    - $R -e "library('RoBMA')"           # [not win]
    - "\"%R%\" -e \"library('RoBMA')\""  # [win]

about:
  home: https://fbartos.github.io/RoBMA/
  license: GPL-3.0-only
  summary: A framework for estimating ensembles of meta-analytic models (assuming either presence or absence of the effect, heterogeneity, and publication bias) and using Bayesian model averaging to combine them. The ensembles use Bayes factors to test for the presence or absence of the individual components (e.g., effect
    vs. no effect) and model-averages parameter estimates based on posterior model probabilities (Maier, Bartoš & Wagenmakers, 2020, <doi:10.31234/osf.io/u4cns>). The user can define a wide range of non-informative or informative priors for the effect size, heterogeneity, and weight functions. The package provides convenient
    functions for summary, visualizations, and fit diagnostics.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
